name: "Cypress Summary"
description: "Adds a summary of specs run by Cypress via an issue comment"
icon: alert-triangle
color: green
inputs:
  pathname:
    description: "Full pathname to the mochawesome report JSON file"
    required: true
  title:
    description: "Title for the comment"
    default: "## :evergreen_tree: Cypress report"
    required: false
outputs:
  commentBody:
    description: "Body of the comment to be used"
runs:
  using: "node12"
  main: "index.js"
